--2. 동물병원의 요구사항은 다음과 같다
--- 동물병원의 반려동물, 보호자의 정보를 저장하고 관리한다
--- 보호자는 번호, 이름, 주소, 핸드폰 번호, 이메일주소를 가진다
--- 반려동물은 번호, 이름, 성별, 나이, 종, 품종, 보호자 번호를 가진다
--- 모든 보호자는 중복이 없는 번호를 가진다 O
--- 보호자의 이름, 주소, 핸드폰 번호는 필수 정보이다 O
--- 모든 동물은 중복이 없는 번호를 가진다 O
--- 동물의 이름, 성별, 나이, 종, 보호자 번호는 필수 정보이다O
--- 동물의 보호자 번호는 실제 존재하는 보호자 번호여야 한다

--
-- 1. 개념적 설계
-- <동물병원>		<보호자>		<반려동물>
-- 반려동물번호		보호자 번호		동물번호
-- 보호자 번호		이름			이름
--				주소			성별
--				보호자핸드폰번호	나이
--							종
--							품종
--							보호자 핸드폰번호
--							보호자 번호
--
-- 2. 논리적 설계
-- <보호자>			<반려동물>			<동물병원>
-- 보호자 번호 PK		동물번호 PK		동물번호 FK   } 
-- 이름 N/N			이름 N/N			보호자번호 FK  } -> 조합키 PK
-- 주소 N/N			성별 N/N
-- 핸드폰번호 N/N		나이 N/N
--					종 N/N
--					품종
--					보호자번호 FK N/N
--
--
--3. 물리적 설계
-- TBL_GUARDIAN
-- GUARDIAN_NUM : NUMBER (PK)
-- GUARDIAN_NAME : VARCHAR2 N/N
-- GUARDIAN_ADDRESS : VARCHAR2 N/N
-- GUARDIAN_PHONE : VARCHAR2 N/N
--
--
-- TBL_ANIMAL
-- ANIMAL_NUM : NUMBER (PK)
-- ANIMAL_NAME : VARCHAR2 N/N
-- ANIMAL_GENDER : CHAR(1) N/N
-- ANIMAL_AGE : NUMBER N/N
-- ANIMAL_SPECIES : VARCHAR2 N/N
-- ANIMAL_BREED : VARCHAR2
-- GUARDIAN_NUM : NUMBER (FK)
--
-- TBL_HOSPITAL
-- GUARDIAN_NUM : NUMBER (FK) }
-- ANIMAL_NUM : NUMBER (FK)   }  -> PK
--
-- 구현

CREATE TABLE TBL_GUARDIAN(
	GUARDIAN_NUM NUMBER,
	GUARDIAN_NAME VARCHAR2(1000) NOT NULL,
	GUARDIAN_ADDRESS VARCHAR2(1000) NOT NULL,
	GUARDIAN_PHONE VARCHAR2(1000) NOT NULL,
	CONSTRAINT PK_GUARDIAN PRIMARY KEY(GUARDIAN_NUM)
);

CREATE TABLE TBL_ANIMAL(
	ANIMAL_NUM NUMBER,
	GUARDIAN_NUM NUMBER,
	ANIMAL_NAME VARCHAR2(1000) NOT NULL,
	ANIMAL_GENDER CHAR(1) NOT NULL CONSTRAINT GENDER_CHECK CHECK(ANIMAL_GENDER = 'M' OR ANIMAL_GENDER = 'F'),
	ANIMAL_AGE NUMBER NOT NULL,
	ANIMAL_SPECIES VARCHAR2(1000) NOT NULL,
	ANIMAL_BREED VARCHAR2(1000),
	CONSTRAINT PK_ANIMAL PRIMARY KEY(ANIMAL_NUM),
	CONSTRAINT FK_GUARDIAN FOREIGN KEY(GUARDIAN_NUM) REFERENCES TBL_GUARDIAN(GUARDIAN_NUM)
);



CREATE TABLE TBL_HOSPITAL(
	GUARDIAN_NUM NUMBER,
	ANIMAL_NUM NUMBER,
	CONSTRAINT FK2_GUARDIAN FOREIGN KEY(GUARDIAN_NUM) REFERENCES TBL_GUARDIAN(GUARDIAN_NUM),
	CONSTRAINT FK2_ANIMAL FOREIGN KEY(ANIMAL_NUM) REFERENCES TBL_ANIMAL(ANIMAL_NUM)
);

ALTER TABLE TBL_HOSPITAL ADD CONSTRAINT PK_COM2 PRIMARY KEY(GUARDIAN_NUM, ANIMAL_NUM)

DROP TABLE TBL_GUARDIAN;
DROP TABLE TBL_ANIMAL;
DROP TABLE TBL_HOSPITAL;

CREATE SEQUENCE SEQ_GUARDIAN;

INSERT INTO TBL_GUARDIAN
--VALUES(SEQ_GUARDIAN.NEXTVAL, 'BAE', 'SEOUL','010-8350-7172')
--VALUES(SEQ_GUARDIAN.NEXTVAL, 'KIM', 'SEOUL','010-1234-5678');
--VALUES(SEQ_GUARDIAN.NEXTVAL, 'PARK', 'GURI','010-2345-6789');
--VALUES(SEQ_GUARDIAN.NEXTVAL, 'LEE', 'KIMPO','010-3456-7890');
VALUES(SEQ_GUARDIAN.NEXTVAL, 'CHOI', 'BUSAN','010-4567-8901');

CREATE SEQUENCE SEQ_ANIMAL;

INSERT INTO TBL_ANIMAL
--VALUES(SEQ_ANIMAL.NEXTVAL, 1, '멍이' , 'M', 2, '강아지', 'A');
--VALUES(SEQ_ANIMAL.NEXTVAL, 1, '냥이' , 'M', 3, '고양이', 'B');
--VALUES(SEQ_ANIMAL.NEXTVAL, 2, '뭉이' , 'F', 4, '강아지', 'A');
--VALUES(SEQ_ANIMAL.NEXTVAL, 3, '학이' , 'F', 5, '새', 'C');
VALUES(SEQ_ANIMAL.NEXTVAL, 3, '달이' , 'M', 8, '치타', 'J');


INSERT INTO TBL_HOSPITAL
--VALUES(1,1);
--VALUES(1, 2);
--VALUES(2,3);
--VALUES(3,4);
--VALUES(3,5);
--VALUES(4,6); --- 오류발생!

SELECT * FROM TBL_GUARDIAN;
SELECT * FROM TBL_ANIMAL;
SELECT * FROM TBL_HOSPITAL;



