--1. 학생 정보와 성적을 관리하기 위해 다음과 같은 정보를 저장해야한다
--- 학생번호, 이름, 나이, 전화번호, 주소
--- 과목명, 강사명, 개강일, 수업시간, 학생성적, 수업번호, 과목번호
--학생 정보 및 성적 관리 시스템
--
--- 학생 정보 관리 요구사항 :
--    - 학생번호, 이름, 나이, 전화번호, 주소 필요
--- 과목 정보 관리 요구사항 :
--    - 과목번호, 과목명, 강사명, 개강일, 수업시간(오전 9시, 오후 19시 중 자유) 필요
--- 성적 정보 관리 요구사항 :
--    - 학생의 성적과 수업번호 저장 필요

--모델링, 정규화, 구현까지 진행 후 각 테이블에 5개씩 값 넣어서 조회까지 할 것!

-- 정규화

-- 1. 개념적 설계
-- <학생>			<과목>		<성적>
-- 학생번호		과목번호		학생번호
-- 이름			과목명		수업번호
-- 나이			강사명		성적
-- 전화번호		개강일
-- 주소			수업시간
--
--
--2. 논리적 설계
-- <학생>			<과목>		<성적>
-- 학생번호(PK)	과목번호(PK)	학생번호(FK) }
-- 이름	N/N		과목명 N/N	과목번호(FK) } -> 조합키로 PK지정
-- 나이	N/N		강사명 		성적 N/N
-- 전화번호 N/N	개강일 
-- 주소	N/N		수업시간 
--
--
--3. 물리적 설계
-- TBL_STUDENT
-- STUDENT_NUM : NUMBER (PK)
-- STUDENT_NAME : VARCHAR2 N/N
-- STUDENT_AGE : NUMBER N/N
-- STUDNET_PHONE_NUM : VARCHAR2 N/N
-- STUDENT_ADDRESS : VARCHAR2 N/N
--
-- TBL_SUBJECT
-- SUBJECT_NUM : NUMBER (PK)
-- SUBJECT_NAME : VARCHAR2 N/N
-- SUBJECT_TEACHER : VARCHAR2
-- SUBJECT_BEGIN : DATE
-- SUBJECT_TIME : DATE
--
--
-- TBL_SCORE
-- STUDENT_NUM  FK
-- SUBJECT_NUM  FK
-- SCORE_GRADE  N/N
--
-- 구현

CREATE TABLE TBL_STUDENT(
	STUDENT_NUM NUMBER,
	STUDENT_NAME VARCHAR2(1000) NOT NULL,
	STUDENT_AGE NUMBER NOT NULL,
	STUDENT_PHONE_NUM VARCHAR2(1000) NOT NULL,
	STUDENT_ADDRESS VARCHAR2(1000) NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NUM)
);

CREATE TABLE TBL_SUBJECT(
	SUBJECT_NUM NUMBER,
	SUBJECT_NAME VARCHAR2(1000) NOT NULL,
	SUBJECT_TEACHER VARCHAR2(1000),
	SUBJECT_BEGIN DATE,
	SUBJECT_TIME VARCHAR2(1000) CONSTRAINT TIME_CHECK CHECK(SUBJECT_TIME = '오전 9시' OR SUBJECT_TIME = '오후 7시'),
	CONSTRAINT PK_SUBJECT PRIMARY KEY(SUBJECT_NUM)
);

CREATE TABLE TBL_SCORE(
	STUDENT_NUM NUMBER,
	SUBJECT_NUM NUMBER,
	SCORE_GRADE CHAR(1) NOT NULL,
	CONSTRAINT FK_STUDENT FOREIGN KEY(STUDENT_NUM) REFERENCES TBL_STUDENT(STUDENT_NUM),
	CONSTRAINT FK_SUBJECT FOREIGN KEY(SUBJECT_NUM) REFERENCES TBL_SUBJECT(SUBJECT_NUM)
);

DROP TABLE TBL_SCORE;
DROP TABLE TBL_SUBJECT;

ALTER TABLE TBL_SCORE ADD CONSTRAINT PK_COM PRIMARY KEY(STUDENT_NUM, SUBJECT_NUM);

INSERT INTO TBL_STUDENT
--VALUES(1,'BAE', 26, '010-8350-7172', 'SEOUL');
--VALUES(2,'KIM', 25, '010-1234-5678', 'SEOUL');
--VALUES(3,'PARK', 24, '010-2345-6789', 'GURI');
--VALUES(4, 'LEE', 23, '010-3456-7890', 'KIMPO');
VALUES(5,'CHOI', 22, '010-4567-8901', 'BUSAN');

CREATE SEQUENCE SEQ_SUBJECT;

INSERT INTO TBL_SUBJECT
--VALUES(SEQ_USER.NEXTVAL, '짱구', 5);
--VALUES(SEQ_SUBJECT.NEXTVAL, '수학', '김T', '2024-09-01', '오전 9시');
--VALUES(SEQ_SUBJECT.NEXTVAL, '영어', '박T', '2024-09-01', '오전 9시');
--VALUES(SEQ_SUBJECT.NEXTVAL, '과학', '최T', '2024-09-01', '오전 9시');
VALUES(SEQ_SUBJECT.NEXTVAL, '체육', '우T', '2024-09-01', '오전 9시');


CREATE SEQUENCE SEQ_SCORE;

INSERT INTO TBL_SCORE
--VALUES(1, 1, 'C');
--VALUES(1, 2, 'C');
--VALUES(1, 3, 'F');
--VALUES(2, 1, 'A');
--VALUES(2, 2, 'A');
VALUES(2, 3, 'B');

SELECT * FROM TBL_STUDENT;
SELECT * FROM TBL_SUBJECT;
SELECT * FROM TBL_SCORE;

