CREATE SEQUENCE SEQ_USER;

-- 사용자 정보 저장하는 유저 테이블 tbl_user
-- 사용자 번호
-- 아이디
-- 패스워드
-- 이름
-- 나이
-- 성별
-- 생일
CREATE TABLE TBL_USER(
	USER_NUMBER NUMBER,
	USER_ID VARCHAR2(100),
	USER_PW VARCHAR2(100),
	USER_NAME VARCHAR2(10),
	USER_AGE NUMBER,
	USER_GENDER CHAR(1) DEFAULT 'M',
	USER_BIRTH DATE,
	CONSTRAINT PK_USER PRIMARY KEY(USER_NUMBER)
);

SELECT * FROM tbl_user;

INSERT INTO TBL_USER
--VALUES(SEQ_USER.NEXTVAL, 'aaa', '1234', '홍길동', 22, 'M', '20001010');
VALUES(SEQ_USER.NEXTVAL, 'bbb', '1234', '배지수', 27, 'M', '19990412');

